[build]
  base = "/frontend"
  publish = "build"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "16.0.0"
  REACT_APP_API_URL = "https://aveo-cafe-backend.onrender.com/api"
  CI = "false"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"